[workspace]

[workspace.dependencies]
polars = {version="0.x", default-features=false, features=["csv","dtype-full","parquet"]}
anyhow = "1.0.x"
serde = { version = "1.0.x",features=["derive"]}
serde_json = "1.0.x"
regex = {version = "1.3"}


[package]
name = "bench-suite-collect"
version = "0.1.0"
edition = "2024"

[dependencies]
bench-suite-config = {path = "./bench-suite-config/"}
bench-suite-types = {path = "./bench-suite-types/"}

anyhow = {workspace = true}
xz2 = "0.1.7"
tar = "0.4.44"
