[package]
name = "bench-suite-collector-time"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = {workspace = true}
bench-suite-types = {path="../../bench-suite-types"}
bench-suite-collect-results = {path="../../bench-suite-collect-results"}
anyhow = {workspace = true}

