[package]
name = "bench-suite-config"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = {workspace = true}
serde = {workspace =  true}
serde_json = {workspace = true}

bench-suite-types = {path = "../bench-suite-types",features=["serde"]}
