[package]
name = "bench-suite-config"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228"}
serde_json = "1.0.149"

bench-suite-types = {path = "../bench-suite-types"}
