[package]
name = "bench-suite-collect-results"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = {workspace = true}
anyhow = {workspace = true}


bench-suite-types = {path = "../bench-suite-types"}
